name: Special

on:
  workflow_dispatch:
    inputs:
      firmware_link:
        description: 'Stock Firmware Link (Direct Download/Wget)'
        required: true
      rom_type:
        description: 'ROM Type'
        required: true
        type: choice
        options:
          - OneUI
          - Pixel
          - MIUIGeneric
          - HyperOS
          - HMD
          - Generic

jobs:
  Link2GSI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false # We handle this manually


      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename liblzma-dev python3-pip brotli lz4 protobuf-compiler git gawk jq
          
      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install protobuf==3.20.3
          
          
      - name: Install Python Dependencies
        run: |
          python3 -m pip install backports.lzma bsdiff4 twrpdtgen extract-dtb pycryptodome
      - name: Prepare and Clean URL
        id: prep
        run: |
          LINK="${{ inputs.firmware_link }}"
          if [[ "$LINK" == *"google.com/url"* ]]; then
             LINK=$(echo "$LINK" | grep -oP 'q=\K[^&]*' | python3 -c "import sys, urllib.parse; print(urllib.parse.unquote(sys.stdin.read().strip()))")
          fi
          echo "url=$LINK" >> $GITHUB_OUTPUT

      - name: Download Firmware
        id: download
        run: |
          wget -q -O firmware.zip "${{ steps.prep.outputs.url }}"
          if [ -f firmware.zip ]; then
            echo "Download Successful."
            du -h firmware.zip
          else
            echo "Download Failed."
            exit 1
          fi
      - name: Make all scripts executable
        run: |
          find . -type f -name "*.sh" -exec chmod +x {} \;
          
      - name: Run LinkToGSI Script
        run: |
          chmod +x LinkToGSI.sh
          bash specialextract.sh "$(pwd)/firmware.zip" "${{ inputs.rom_type }}"

      - name: Upload to PixelDrain
        env:
          PIXELDRAIN_KEY: ${{ secrets.PIXELDRAIN_API_KEY }}
        run: |
          sudo chown -R $USER:$USER .
          FILE=$(ls Output/*.img* | head -n 1)
          echo "Uploading $FILE to PixelDrain securely..."
          RESPONSE=$(curl -u ":$PIXELDRAIN_KEY" -T "$FILE" https://pixeldrain.com/api/file/)
          FILE_ID=$(echo $RESPONSE | jq -r '.id // empty')
          if [ ! -z "$FILE_ID" ]; then
            echo "=========================================="
            echo " Download URL: https://pixeldrain.com/u/$FILE_ID"
            echo "=========================================="
          else
            echo "Upload truly failed! Response from server:"
            echo "$RESPONSE"
            exit 1
          fi
